baseurl = "https://techcultivation.org/"
languageCode = "en-us"
title = "A Non-Profit Home for Open Source Projects"
theme = "hugo-creative-theme"
relativeURLs = true
uglyurls = true

[markup.goldmark.renderer]
unsafe = true

[params]
name = "Center for the Cultivation of Technology"
description = "a non-profit home for open source projects"

# The path must be relative to the static folder
favicon = "favicon.ico"

# Navigation
[params.navigation]
brand = "Center for the Cultivation of Technology"

[[params.navigation.links]]
    url = "./#subscribe"
    text = "Subscribe to News"

[[params.navigation.links]]
    url = "./donate.html"
    text = "Donate"

[[params.navigation.links]]
    url = "./#overview"
    text = "Overview"

[[params.navigation.links]]
    url = "./contact.html#team"
    text = "Team"

[[params.navigation.links]]
    url = "./contact.html"
    text = "Contact"

# Hero section
[params.hero]
slogan     = "A non-profit home<br/> for your open source project"
subtitle   = "The Center for the Cultivation of Technology is a charitable non-profit<br/> host organization for international Free Software projects."
buttonText = "Learn more"

# About section
[params.about]
headline    = "Interested? Get in touch!"
description = "We are ready for your project if you need <a href=\"contact.html\">help with grants and contracts</a>.<br/><br/>It will take us a while to build a platform to allow projects to easily interface with their budgets, and before we can manage individual donations to projects. Leave your e-mail address and we will get in touch as soon as we're there!"

# Overview section
[params.overview]
headline = "Overview"
 
[[params.overview.list]]
icon = "far fa-heart"
title = "Donations"
description = "Receive donations via various payment processors and fundraising platforms."
 
[[params.overview.list]]
icon = "far fa-money-bill-alt"
title = "Budget management"
description = "Manage and allocate budgets, process reimbursements, contract and employ internationally."
 
[[params.overview.list]]
icon = "fas fa-cubes"
title = "Asset Stewardship"
description = "The Center can hold assets for a project, such as domain names, trademarks and copyright."
 
[[params.overview.list]]
icon = "far fa-comment-dots"
title = "Expert Network"
description = "Knowledge sharing and exchange."
